### ISSUE TITLE
problem with import in python 3

### ISSUE THREAD

**Issue by MarxUa** [AutomatedTester/browsermob-proxy-py#29]
I try to:
import browsermobproxy

but have:
Traceback (most recent call last):
  File "C:/Users/Myalee/Desktop/Prog/JetBrains PyCharm 3.4.1/Json/selenium_second.py", line 1, in <module>
    import browsermobproxy 
  File "C:\Python34\lib\site-packages\browsermobproxy\__init__.py", line 3, in <module>
    from server import Server
ImportError: No module named 'server'

It's work fine in python 2.7, but not in 3.4

**Comment by SenadI** [comment]
I can confirm this.

**Comment by AutomatedTester** [comment]
Is this still an issue. My tests on travis are passing. Please reopen if it is still an issue
