### ISSUE TITLE
Can not connect to BrowserMob Proxy

### ISSUE THREAD

**Issue by DriveU** [AutomatedTester/browsermob-proxy-py#35]
Server server = new Server(@"D:\NDrive\GR\MiscTest\BrowserMob-Tests\browsermob-proxy-master\browsermob-dist\src\main\scripts\browsermob-proxy.bat");
			server.Start();

			Client client = server.CreateProxy();
			client.RemapHost("host", "ip address");
			client.NewHar("google");

			var seleniumProxy = new Proxy { HttpProxy = client.SeleniumProxy };
			var profile = new FirefoxProfile();
			profile.SetProxyPreferences(seleniumProxy);
			// Navigate to the page to retrieve performance stats for
			var driver = new FirefoxDriver(profile);
			driver.Navigate().GoToUrl("http://google.com");

			// Get the performance stats
			HarResult harData = client.GetHar();

			AutomatedTester.BrowserMob.HAR.Log log = harData.Log;
			AutomatedTester.BrowserMob.HAR.Entry[] entries = log.Entries;
			foreach (var entry in entries)
			{
				AutomatedTester.BrowserMob.HAR.Request request = entry.Request;
				var url = request.Url;
				var time = entry.Time;
				Console.WriteLine("Url: " + url + " - Time: " + time);
			}
			driver.Quit();
			client.Close();
			server.Stop();

Message : {"Can not connect to BrowserMob Proxy"}
   at AutomatedTester.BrowserMob.Server.Start() in D:\NDrive\GR\MiscTest\BrowserMob-Tests\AutomatedTester.BrowserMob-master\AutomatedTester.BrowserMob\Server.cs:line 54
   at MobTester.Program.Main(String[] args) in D:\NDrive\GR\MiscTest\BrowserMob-Tests\MobTester\MobTester\Program.cs:line 14
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
WHAT IS WRONG IN THIS? PLEASE GET BACK TO ME ASAP

**Comment by pronojitsaha** [comment]
Hi,

I have the following:
```
from browsermobproxy import Server
server = Server("/Users/username/Desktop/browsermob-proxy/bin/browsermob-proxy")
server.start()
proxy = server.create_proxy() 
```

I'm getting the same error on server.start().
```Exception: Can't connect to Browsermob-Proxy```

Further on terminal, if I do ```/Users/username/Desktop/browsermob-proxy/bin/browsermob-proxy -port 9090``` I get the following error:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/lightbody/bmp/proxy/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```
It seems to be some issue with the version number, but not sure what exactly it is. Thanks.
