### ISSUE TITLE
Cannot install browsermobproxy with pip nor python -m pip

### ISSUE THREAD

**Issue by Luckytrang2010** [AutomatedTester/browsermob-proxy-py#96]
```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Trang\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Trang\\AppData\\Local\\Temp\\pip-install-bj1ivg7n\\browsermobproxy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Trang\\AppData\\Local\\Temp\\pip-install-bj1ivg7n\\browsermobproxy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Trang\AppData\Local\Temp\pip-record-983oxeji\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Trang\AppData\Local\Programs\Python\Python38\Include\browsermobproxy'
         cwd: C:\Users\Trang\AppData\Local\Temp\pip-install-bj1ivg7n\browsermobproxy\
    Complete output (14 lines):
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Trang\AppData\Local\Temp\pip-install-bj1ivg7n\browsermobproxy\setup.py", line 32, in <module>
        setup(
      File "C:\Users\Trang\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Trang\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Trang\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Trang\AppData\Local\Temp\pip-install-bj1ivg7n\browsermobproxy\setup.py", line 20, in run
        raise Exception("You probably meant to install and run browsermob-proxy")
    Exception: You probably meant to install and run browsermob-proxy
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Trang\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Trang\\AppData\\Local\\Temp\\pip-install-bj1ivg7n\\browsermobproxy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Trang\\AppData\\Local\\Temp\\pip-install-bj1ivg7n\\browsermobproxy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Trang\AppData\Local\Temp\pip-record-983oxeji\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Trang\AppData\Local\Programs\Python\Python38\Include\browsermobproxy' Check the logs for full command output.
```
So basically, I got this error when I was trying to install _browsermobproxy_. How do I fix this?

**Comment by Luckytrang2010** [comment]
nvm
